#!/bin/sh
docker network create ubuntu &> /dev/null
docker volume create docker > /dev/null && docker volume create mongodb > /dev/null && docker volume create nginx > /dev/null && docker volume create ubuntu > /dev/null && docker run -it --rm --privileged --net=ubuntu -v mongodb:/var/lib/mongodb -v docker:/var/lib/docker -v nginx:/etc/nginx -v ubuntu:/home/ubuntu -v $HOME:/home/ubuntu/host:cached $UBUNTU_PARAMS "$@" josei/ubuntu
